! subroutine CalDdatSigma(dall,obst,cbst,sigmaT,meandeltaT,stddeltaT)
subroutine CalDdatSigma(dall, obst, cbst, sigmaT, meandeltaT)
implicit none
! abandoned
! used in Yunnan
! INPUT
integer dall
real obst(dall),cbst(dall)
! OUTPUT
real  sigmaT(dall)
real meandeltaT,stddeltaT
! PARAMETER
integer jj,kk,ii
integer i,j,k
real twostdratio
real :: deltaT(dall)
real, parameter :: obs_floor = 1.0e-6
real, parameter :: std_floor = 1.0e-6
real, parameter :: sigma_floor = 1.0e-6
! sigma(i)=std(t_res/t_obs)*t_obs
deltaT=0
meandeltaT=0

do i = 1,dall
    deltaT(i)=abs(cbst(i))/max(abs(obst(i)), obs_floor)
    meandeltaT=meandeltaT+deltaT(i)
enddo
meandeltaT=meandeltaT/dall
! meandeltaT=sum(deltaT(1:dall))/dall
stddeltaT=0
do i=1,dall
    stddeltaT=stddeltaT+(deltaT(i)-meandeltaT)**2
enddo
stddeltaT=max(sqrt(stddeltaT/dall), std_floor)
! stddeltaT=sqrt(sum((deltaT(1:dall)-meandeltaT)**2))
do i=1,dall
    twostdratio=abs(deltaT(i)/(1.5*stddeltaT))
    if (twostdratio.gt.1.0)then
        sigmaT(i)=stddeltaT*max(abs(obst(i)), obs_floor)*exp(twostdratio-1)
    else
        sigmaT(i)=stddeltaT*max(abs(obst(i)), obs_floor)
    endif
    sigmaT(i)=max(sigmaT(i), sigma_floor)
enddo
end subroutine

! Residual Norm !
! Active residual diagnostics use CalSparseReslNorm below.  The dense
! GVs/GGc/GGs routines are retained only for reading old experiments and for
! manual A/B checks against archived dense-matrix workflows.
!
! LEGACY-DENSE: do not call from active inversion code. These routines require
! dall*maxvp dense diagnostic matrices and defeat the sparse-memory path.
subroutine CalVsReslNorm(maxvp,dall,GVs,VsInv,datweight,Tdata,fwdTvs,resbst)
    use  lsmrblasInterface, only : dnrm2
    implicit none
    ! INPUT
    integer,intent(in):: dall,maxvp
    real,intent(in):: GVs(dall,maxvp)
    ! real,intent(in):: dv(maxvp),datweight(dall),Tdata(dall)
    real,intent(in):: VsInv(maxvp),datweight(dall),Tdata(dall)
    ! OUTPUT
    real:: resbst(dall)

    real:: resW2Nm,res2Nm
    real:: PreRes
    ! PARAMETER

    real fwdTgc(dall),fwdTgs(dall), fwdTvs(dall),fwdt(dall)
    real fwdTaa(dall),res(dall),resW(dall),per_res(dall)
    integer jj,kk,ii
    integer i,j,k
    !--------------------------------------------------------------------!
    ! Target:
    !  Calculate traveltime resiudal between observe traveltime
    !  and forward traveltime which is generated by inversion result
    !  using G from ref  model.
    !   r=Gm-d
    !--------------------------------------------------------------------!
    ! VsInv=dv(1:maxvp)
    !--------------------------------------------------------------------!
    ! forward residual
    fwdTvs=matmul(GVs,VsInv)
    fwdt=0
    res=0
    resW=0
    per_res=0
    resbst=0
    do i=1,dall
        resbst(i)=Tdata(i)-fwdTvs(i)
        resW(i)=resbst(i)*datweight(i) ! here, 1/sigma is for
        per_res(i)=resbst(i)/Tdata(i)
    enddo
    resW2Nm=dnrm2(dall,resW,1)
    res2Nm=dnrm2(dall,resbst,1)
    PreRes=sum(abs(per_res(1:dall)))/dall

    write(6 ,'(a,2f12.3)') '  dVs:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
    write(66,'(a,2f12.3)') '  dVs:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
    ! write(6,*) ' abs mean Res(Vs)/Res  (%)',PreRes*100
    ! write(66,*)' abs mean Res(Vs)/Res  (%)',PreRes*100
end subroutine

subroutine CalSparseReslNorm(m, n, maxvp, dall, leniw, lenrw, iw, rw, dv, datweight, Tdata, &
                             fwdTvs, fwdTaa, resbst, iso_inv)
    use  lsmrblasInterface, only : dnrm2
    implicit none
    integer,intent(in) :: m,n,maxvp,dall
    integer(kind=8),intent(in) :: leniw,lenrw
    integer,intent(in) :: iw(leniw)
    real,intent(in) :: rw(lenrw),dv(n),datweight(dall),Tdata(dall)
    logical,intent(in) :: iso_inv
    real,intent(out) :: fwdTvs(dall),fwdTaa(dall),resbst(dall)

    real,allocatable :: xpart(:),fwdAll(:),resW(:)
    real :: res2Nm,resW2Nm,mean
    integer :: i
    external aprod

    if ((.not. iso_inv) .and. (n .lt. 3*maxvp)) then
        stop 'CalSparseReslNorm: joint inversion requires n >= 3*maxvp'
    endif

    allocate(xpart(n),fwdAll(m),resW(dall))
    fwdTvs = 0.0
    fwdTaa = 0.0

    xpart = 0.0
    fwdAll = 0.0
    xpart(1:maxvp) = dv(1:maxvp)
    call aprod(1, m, n, xpart, fwdAll, leniw, lenrw, iw, rw)
    do i=1,dall
        if (abs(datweight(i)) <= tiny(datweight(i))) stop 'CalSparseReslNorm: zero data weight'
        fwdTvs(i) = fwdAll(i) / datweight(i)
    enddo

    if (.not. iso_inv) then
        xpart = 0.0
        fwdAll = 0.0
        xpart(maxvp+1:2*maxvp) = dv(maxvp+1:2*maxvp)
        call aprod(1, m, n, xpart, fwdAll, leniw, lenrw, iw, rw)
        do i=1,dall
            fwdTaa(i) = fwdAll(i) / datweight(i)
        enddo

        xpart = 0.0
        fwdAll = 0.0
        xpart(2*maxvp+1:3*maxvp) = dv(2*maxvp+1:3*maxvp)
        call aprod(1, m, n, xpart, fwdAll, leniw, lenrw, iw, rw)
        do i=1,dall
            fwdTaa(i) = fwdTaa(i) + fwdAll(i) / datweight(i)
        enddo
    endif

    resbst(1:dall) = Tdata(1:dall) - fwdTvs(1:dall) - fwdTaa(1:dall)
    resW(1:dall) = resbst(1:dall) * datweight(1:dall)
    resW2Nm = dnrm2(dall,resW,1)
    res2Nm = dnrm2(dall,resbst,1)

    if (iso_inv) then
        write(6 ,'(a,2f12.3)') '  dVs:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
        write(66,'(a,2f12.3)') '  dVs:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
    else
        write(6 ,'(a,2f12.3)') '  All:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
        write(66,'(a,2f12.3)') '  All:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
        write(66,'(a)')'  '
        write(6 ,'(a)')'  '
        mean=sum(abs(fwdTaa(1:dall)))/dall
        write(66,'(a,f12.4,a)')'  ABS Mean T(AA): ',mean,'s'
        write(6 ,'(a,f12.4,a)')'  ABS Mean T(AA): ',mean,'s'
        mean=sum(abs(fwdTvs(1:dall)))/dall
        write(66,'(a,f12.4,a)')'  ABS Mean T(dVs):',mean,'s'
        write(6 ,'(a,f12.4,a)')'  ABS Mean T(dVs):',mean,'s'
    endif

    deallocate(xpart,fwdAll,resW)
end subroutine


! LEGACY-DENSE: use CalSparseReslNorm for active code. This routine requires
! dense GGc/GGs matrices and is kept only for archived workflows.
subroutine CalGcsReslNorm(maxvp,dall,GGc,GGs, GcInv, GsInv, datweight,Tdata,fwdTaa,resbst)
    use  lsmrblasInterface, only : dnrm2
    implicit none
    ! resW2Nm: predicated ||W(Gm-d)||2
    ! res2Nm: predicated ||(Gm-d)||2
    ! INPUT
    integer,intent(in):: dall,maxvp
    real,intent(in):: GGc(dall,maxvp),GGs(dall,maxvp)
    real,intent(in):: GcInv(maxvp), GsInv(maxvp), datweight(dall),Tdata(dall)
    ! OUTPUT
    real:: resbst(dall)
    real:: res2Nm,resW2Nm
    real:: PreRes
    ! PARAMETER
    ! real VsInv(maxvp),GcInv(maxvp),GsInv(maxvp)
    real fwdTgc(dall),fwdTgs(dall), fwdTvs(dall),fwdt(dall)
    real fwdTaa(dall),res(dall),resW(dall),per_res(dall)
    integer jj,kk,ii
    integer i,j,k
    real norm2,norm2W
    !--------------------------------------------------------------------!
    ! Target:
    !  Calculate traveltime resiudal between observe traveltime
    !  and forward traveltime which is generated by inversion result
    !  using G from ref  model.
    !   r=Gm-d
    !--------------------------------------------------------------------!
    ! GcInv=dv(1:maxvp)
    ! GsInv=dv(1+maxvp:2*maxvp)
    !--------------------------------------------------------------------!
    ! forward residual
    fwdTgc=matmul(GGc,GcInv)
    fwdTgs=matmul(GGs,GsInv)
    fwdTaa=0
    res=0
    resW=0
    per_res=0
    resbst=0
    norm2=0
    norm2W=0
    do i=1,dall
        fwdTaa(i)=fwdTgs(i)+fwdTgc(i)
        resbst(i)=Tdata(i)-fwdTaa(i)
        resW(i)=resbst(i)*datweight(i) ! here, 1/sigma is for data weight
        if (Tdata(i) .gt. 0)   per_res(i)=resbst(i)/Tdata(i)
        ! norm2=norm2+resbst(i)**2
        ! norm2W=norm2W+resW(i)**2
        ! write(6,*)'res=',resbst(i),'weight=',datweight(i),'resW=',resW(i),'norm2=',norm2,'norm2W=',norm2W
    enddo
    resW2Nm=dnrm2(dall,resW,1)
    res2Nm=dnrm2(dall,resbst,1)
    PreRes=sum(abs(per_res(1:dall)))/dall
    write(6 ,'(a,2f12.3)') '  Gcs:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
    write(66,'(a,2f12.3)') '  Gcs:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
    ! write(6,*) ' abs mean Res(aa)/Res  (%)',PreRes*100
    ! write(66,*)' abs mean Res(aa)/Res  (%)',PreRes*100
end subroutine


! LEGACY-DENSE: use CalSparseReslNorm for active code. This routine requires
! dense GVs/GGc/GGs matrices and is kept only for archived workflows.
subroutine CalReslNormJoint(maxvp, dall, GVs, GGc, GGs, VsInv, GcInv, GsInv, datweight, Tdata, fwdTvs, fwdTaa, resbst)
    use  lsmrblasInterface, only : dnrm2
    implicit none
    ! resW2Nm: predicated ||W(Gm-d)||2
    ! res2Nm: predicated ||(Gm-d)||2
    ! INPUT
    integer,intent(in):: dall,maxvp
    real,intent(in):: GVs(dall,maxvp), GGc(dall,maxvp), GGs(dall,maxvp)
    real,intent(in):: VsInv(maxvp), GcInv(maxvp), GsInv(maxvp), datweight(dall),Tdata(dall)
    ! OUTPUT
    real:: resbst(dall)
    real:: fwdTvs(dall),fwdTaa(dall)
    ! PARAMETER
    ! real VsInv(maxvp),GcInv(maxvp),GsInv(maxvp)
    real fwdTgc(dall),fwdTgs(dall),fwdt(dall)
    real res(dall),resW(dall),per_res(dall)
    integer jj,kk,ii
    integer i,j,k
    real norm2,norm2W
    real:: res2Nm,resW2Nm
    real:: PreRes
    real:: mean
    !--------------------------------------------------------------------!
    ! Target:
    !  Calculate traveltime resiudal between observe traveltime
    !  and forward traveltime which is generated by inversion result
    !  using G from ref  model.
    !   r=Gm-d
    !--------------------------------------------------------------------!
    ! GcInv=dv(1:maxvp)
    ! GsInv=dv(1+maxvp:2*maxvp)
    !--------------------------------------------------------------------!
    ! forward residual
    fwdTvs=matmul(GVs,VsInv)
    fwdTgc=matmul(GGc,GcInv)
    fwdTgs=matmul(GGs,GsInv)
    fwdTaa=0
    res=0
    resW=0
    per_res=0
    resbst=0
    norm2=0
    norm2W=0
    do i=1,dall
        fwdTaa(i)=fwdTgs(i)+fwdTgc(i)
        resbst(i)=Tdata(i)-fwdTaa(i)-fwdTvs(i)
        resW(i)=resbst(i)*datweight(i) ! here, 1/sigma is for

        ! norm2=norm2+resbst(i)**2
        ! norm2W=norm2W+resW(i)**2
        ! write(6,*)'res=',resbst(i),'weight=',datweight(i),'resW=',resW(i),'norm2=',norm2,'norm2W=',norm2W
    enddo
    resW2Nm=dnrm2(dall,resW,1)
    res2Nm=dnrm2(dall,resbst,1)


    write(6 ,'(a,2f12.3)') '  All:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
    write(66,'(a,2f12.3)') '  All:  ||(Gm-d)||^2  and ||W(Gm-d)||^2: ', res2Nm, resW2Nm
    write(66,'(a)')'  '
    write(6 ,'(a)')'  '
    ! analysis residual
    mean=sum(abs(fwdTaa(1:dall)))/dall
    write(66,'(a,f12.4,a)')'  ABS Mean T(AA): ',mean,'s'
    write(6 ,'(a,f12.4,a)')'  ABS Mean T(AA): ',mean,'s'
    mean=sum(abs(fwdTvs(1:dall)))/dall
    write(66,'(a,f12.4,a)')'  ABS Mean T(dVs):',mean,'s'
    write(6 ,'(a,f12.4,a)')'  ABS Mean T(dVs):',mean,'s'
end subroutine


! Model Norm !

subroutine Calmodel2Norm(nar1,nar,maxvp,count3,rw,col,dv,weight)
    use  lsmrblasInterface, only : dnrm2
    implicit none
    ! works for both Vs and Gcs inversion.
    integer(kind=8),intent(in) ::nar1,nar
    integer,intent(in) ::maxvp,count3
    real rw(*)
    integer col(*)
    real,intent(in):: dv(*)
    real,intent(in):: weight
    ! OUTPUT
    real Mnorm2,MwNorm2
    ! PARAMETER
    integer jj,kk,ii
    integer i,j,k
    real Lm(count3),LmWeight(count3)
    integer numC
    ! LOGICAL:: isTikh
    !--------------------------------------------------------------------!
    ! count3: row number of L
    ! Formula: Lm=[a12(m1-m2)
    !                              a13(m1-m3)]
    ! nar1: number of  nonzero value of G
    ! nar: number of nonzero value of Gbar-E
    ! dv: inversion result
    ! rw: value of Gbar
    ! iw2: row number of Gbar, not contain column
    ! col: column number of Gbar
    ! Mnorm2: 2 norm of Lm
    ! numC: count index of  nonzero L
    ! weight: in L, weight has added to Gbar, so divide weight
    ! Regularization Type: (T) 1st order Tikhonov ;(F) Gaussian
    Lm=0
    LmWeight=0

    do i=1,count3
      numC=nar1+i
      Lm(i)=rw(numC)*dv(col(numC))/weight
      LmWeight(i)=rw(numC)*dv(col(numC))
    enddo
    Mnorm2=dnrm2(count3,Lm,1)
    MwNorm2=dnrm2(count3,LmWeight,1)

    ! open(90,file='Lnorm.txt')
    ! do i=1,count3
    ! numC=nar1+i*2-1
    ! write(90,*)numC,col(numC),col(numC+1),dv(col(numC)),dv(col(numC+1)),rw(numC),rw(numC+1)
    ! enddo
    ! close(90)
    !
    ! open(90,file='dv_output.txt')
    ! do i=1,maxvp
    ! write(90,*)dv(i),dv(i+maxvp),dv(i+maxvp*2)
    ! enddo
    ! close(90)

    write(6 ,'(a,2f12.3)') '  dVs:  ||Lm||^2      and ||wLm||^2    : ', Mnorm2, MwNorm2
    write(66,'(a,2f12.3)') '  dVs:  ||Lm||^2      and ||wLm||^2    : ', Mnorm2, MwNorm2
end subroutine

subroutine Calmodel2NormJoint(nar1,nar,maxvp, NreVs, Nre, rw,col,dv, lameGcs, lameVs)
    use  lsmrblasInterface, only : dnrm2
    implicit none
    ! INPUT
    ! NreVs: number of Vs regularization in G
    ! Nre  : number of regularization in G
    integer(kind=8),intent(in) ::nar1,nar
    integer,intent(in) ::maxvp, Nre, NreVs
    real rw(*)
    integer col(*)
    real,intent(in):: dv(*)
    real,intent(in):: lameGcs,lameVs
    ! OUTPUT
    real Mnorm2,MwNorm2
    real VsNorm2,VswNorm2
    real GcsNorm2,GcswNorm2
    ! PARAMETER
    integer jj,kk,ii
    integer i,j,k
    real Lm(Nre), LmWeight(Nre)
    integer(kind=8) numC
    ! LOGICAL:: isTikh
    !--------------------------------------------------------------------!
    ! count3: row number of L
    ! Formula: Lm=[a12(m1-m2)
    !                              a13(m1-m3)]
    ! nar1: number of  nonzero value of G
    ! nar: number of nonzero value of Gbar-E
    ! dv: inversion result
    ! rw: value of Gbar
    ! iw2: row number of Gbar, not contain column
    ! col: column number of Gbar
    ! Mnorm2: 2 norm of Lm
    ! numC: count index of  nonzero L
    ! weight: in L, weight has added to Gbar, so divide weight
    ! Regularization Type: (T) 1st order Tikhonov ;(F) Gaussian
    Lm=0
    LmWeight=0

    do i=1, NreVs
      numC=nar1+i
      Lm(i)=rw(numC)*dv(col(numC))/lameVs
      LmWeight(i)=rw(numC)*dv(col(numC))
    enddo
    VsNorm2=dnrm2(NreVs, Lm(1:NreVs), 1)
    VswNorm2=dnrm2(NreVs, LmWeight(1:NreVs), 1)

    do i=NreVs+1, Nre
      numC=nar1+i
      Lm(i)=rw(numC)*dv(col(numC))/lameGcs
      LmWeight(i)=rw(numC)*dv(col(numC))
    enddo

    GcsNorm2 = dnrm2(Nre-NreVs, Lm(NreVs+1:Nre), 1)
    GcswNorm2= dnrm2(Nre-NreVs, LmWeight(NreVs+1:Nre), 1)

    Mnorm2=dnrm2(Nre, Lm, 1)
    MwNorm2=dnrm2(Nre, LmWeight, 1)


    write(6 ,'(a,2f12.3)') '  dVs:  ||Lm||^2   and   ||wLm||^2     : ', VsNorm2, VswNorm2
    write(66,'(a,2f12.3)') '  dVs:  ||Lm||^2   and   ||wLm||^2     : ', VsNorm2, VswNorm2
    write(6 ,'(a,2f12.3)') '  Gcs:  ||Lm||^2   and   ||wLm||^2     : ', GcsNorm2, GcswNorm2
    write(66,'(a,2f12.3)') '  Gcs:  ||Lm||^2   and   ||wLm||^2     : ', GcsNorm2, GcswNorm2
    write(6 ,'(a,2f12.3)') '  All:  ||Lm||^2   and   ||wLm||^2     : ', Mnorm2, MwNorm2
    write(66,'(a,2f12.3)') '  All:  ||Lm||^2   and   ||wLm||^2     : ', Mnorm2, MwNorm2
    write(66,'(a)')'  '
    write(6 ,'(a)')'  '
end subroutine
