#!/usr/bin/env python3
"""Create iso/ani x voro/novoro DAzi acceptance cases from one template."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


COMBOS = {
    "iso_novoro": {"iso": "T", "voro": "0"},
    "ani_novoro": {"iso": "F", "voro": "0"},
    "iso_voro": {"iso": "T", "voro": "1"},
    "ani_voro": {"iso": "F", "voro": "1"},
}


def rewrite_value(line: str, value: str) -> str:
    comment_at = line.find("c:")
    comment = line[comment_at:] if comment_at >= 0 else ""
    return f"{value:<36} {comment}".rstrip()


def rewrite_para(
    src: Path,
    dst: Path,
    iso_mode: str,
    voro_mode: str,
    maxiter: int,
    normal_cells: int,
    adaptive_cells: int,
    nrealizations: int,
    nzrand: int,
) -> None:
    out: list[str] = []
    found = {
        "maxiter": False,
        "iso": False,
        "voro": False,
        "normal_cells": False,
        "adaptive_cells": False,
        "nrealizations": False,
        "nzrand": False,
    }
    for line in src.read_text(encoding="utf-8").splitlines():
        if "c: maximum of interation" in line:
            out.append(rewrite_value(line, str(maxiter)))
            found["maxiter"] = True
        elif "c: iso-mode" in line:
            out.append(rewrite_value(line, iso_mode))
            found["iso"] = True
        elif "c: voronoi mode" in line:
            out.append(rewrite_value(line, voro_mode))
            found["voro"] = True
        elif "c: normal voro cell number" in line:
            out.append(rewrite_value(line, str(normal_cells)))
            found["normal_cells"] = True
        elif "c: adaptive voro cell number" in line:
            out.append(rewrite_value(line, str(adaptive_cells)))
            found["adaptive_cells"] = True
        elif "c: number of realizations" in line:
            out.append(rewrite_value(line, str(nrealizations)))
            found["nrealizations"] = True
        elif "c: voronoi cell layer number" in line:
            out.append(rewrite_value(line, str(nzrand)))
            found["nzrand"] = True
        else:
            out.append(line)
    missing = [name for name, was_found in found.items() if not was_found]
    if missing:
        raise ValueError(f"{src} is missing expected para.in fields: {', '.join(missing)}")
    dst.write_text("\n".join(out) + "\n", encoding="utf-8")


def copy_case(src: Path, dst: Path, force: bool) -> None:
    if dst.exists():
        if not force:
            raise FileExistsError(f"{dst} exists; pass --force or choose another --out-root")
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def write_matrix_config(out_root: Path, args: argparse.Namespace) -> Path:
    path = out_root / "acceptance_matrix.conf"
    lines = [
        "# Generated by make_four_combo_cases.py",
        "",
    ]
    for combo in COMBOS:
        lines.append(f"{combo} = {out_root / combo}")
    lines.extend(
        [
            "",
            f"threads = {args.threads}",
            f"omp_threads = {args.omp_threads}",
            f"ti_workers = {args.ti_workers}",
            f"tile_columns = {args.tile_columns}",
            f"ti_tile_columns = {args.ti_tile_columns}",
            "infile = para.in",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description="Build four DAzi acceptance cases from one template")
    parser.add_argument("--source-case", type=Path, required=True)
    parser.add_argument("--out-root", type=Path, required=True)
    parser.add_argument("--maxiter", type=int, default=1)
    parser.add_argument("--normal-cells", type=int, default=10)
    parser.add_argument("--adaptive-cells", type=int, default=5)
    parser.add_argument("--nrealizations", type=int, default=1)
    parser.add_argument("--nzrand", type=int, default=4)
    parser.add_argument("--threads", default="4")
    parser.add_argument("--omp-threads", default="4")
    parser.add_argument("--ti-workers", default="4")
    parser.add_argument("--tile-columns", default="64")
    parser.add_argument("--ti-tile-columns", default="64")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    source_case = args.source_case.expanduser().resolve()
    out_root = args.out_root.expanduser().resolve()
    if not (source_case / "para.in").exists():
        raise FileNotFoundError(source_case / "para.in")
    out_root.mkdir(parents=True, exist_ok=True)

    for combo, settings in COMBOS.items():
        dst = out_root / combo
        copy_case(source_case, dst, args.force)
        rewrite_para(
            source_case / "para.in",
            dst / "para.in",
            settings["iso"],
            settings["voro"],
            args.maxiter,
            args.normal_cells,
            args.adaptive_cells,
            args.nrealizations,
            args.nzrand,
        )
        print(f"wrote {dst}")

    matrix_config = write_matrix_config(out_root, args)
    print(f"matrix_config={matrix_config}")


if __name__ == "__main__":
    main()
